### ISSUE TITLE
GUI Integration needed.

### ISSUE THREAD

**Issue by thekaleidoscope** [SatoshiNextTechLab/Decentralized-Lib#2]
Create a GUI for this project with any good language, framework or library.

**Comment by marvisamps** [comment]
Could you give more details about this issue, please?

**Comment by thekaleidoscope** [comment]
Sure, the back-end is a ethereum blockchain, you will need to use web3.js to interact with the backend. You can build the frontend with any library like react or just use javascript with jquery. I'll update the code with better documentation of function workflow.

**Comment by mikgross** [comment]
I am working with web3 already and angular. MIght want to use a different framework tho.
It looks like quite a big issue with no definition at all of the requirements. What do you have in mind for the GUI?
